version: "3.9"

services:
  husarion-office:
    image: husarion/husarion-world:foxy
    runtime: nvidia
    environment:
        - "DISPLAY"
        - "QT_X11_NO_MITSHM=1"
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 launch husarion_office_gz husarion_office_world.launch.py
